### PR TITLE
fix: conflicting states for boxes with identical labels (Fixes #4)

### LINKED ISSUE #4: Boxes won't open properly when there are multiple with the same label
Must have regressed in 4a6686bcab660b9829b115a6dd6d1e05907d1ee8. I dunno know to fix this since the feature was already sorta hacky and I have no idea how else to keep it implemented.

### LINKED ISSUE #5: Box icon does not reflect its actual state on content reparse
### Steps to reproduce
1. Go to https://noelletgs.github.io/osu-bbcode-editor (Commit https://github.com/NoelleTGS/osu-bbcode-editor/commit/8c2a73fabfb0afc5bffa9c6a4019a14d6211ca43 as of issue submission)
2. Paste this sample BBCode
```bbcode
[box=Example]
This is the content of the box labeled "Example."
[/box]
```
3. Open the box if is closed.
4. Modify the current BBCode on the left pane with anything you want, a simple whitespace will do.
For instance I will type the character `a` for the contents in the right pane to refresh.
```bbcode
[box=Example]
This is the content of the box labeled "Example."
[/box]a
```
### Expected behavior
Icon should reflect the box's state.

### Actual behavior
By default on how it was initially written it is open, but the icon does not reflect and retain its "opened" state.

### Relevant code worht mentioning in the repository
This is the most likely area the issue stems from.
https://github.com/NoelleTGS/osu-bbcode-editor/blob/8c2a73fabfb0afc5bffa9c6a4019a14d6211ca43/js/index.js#L179

### PR DESCRIPTION
**Pull request by xayanide**
Open for further suggestions, feel free to point out any errors I may have missed, and suggest any changes if needed.

Fixes #4 
`Fixes #5` This PR aimed to fix these two issues but this was fixed right after this PR with https://github.com/NoelleTGS/osu-bbcode-editor/commit/d7eb86bfa4761463054fbb8d92e421aa0b5a2f76)

- Each box label gets a unique ID by adding a simple counter at the end of the name.
- Adds `boxCounter` parameter to createBox function.
- Replaces the use of string concatenation with template literals for boxId.
- Update box icon based on open/closed state

Tested with sample BBCode
```bbcode
[box=Example]
This is the content of the box labeled "Example."
[/box]

[box=Example]
This is the content of another box labeled "Example."
[/box]

[box=Example]
This is the content of another box labeled "Example."
[/box]
```

### CODE REVIEW

**Comment by xayanide** [comment]
Resolving conflicts in a bit or I might just re-pr this with the one commit only fixing #4

**Comment by xayanide** [comment]
Alright, rebased it.

**Review by NoelleTGS — COMMENTED** [review]
I like your idea of using the box counter and it definitely works better than what I originally had but still isn't without issue. If you have open boxes and then insert a new box before one of the others, it will open the new box as it steals the counter from the box that previously had it.

https://github.com/user-attachments/assets/f297cc32-b485-42e1-a0c7-29ee55d98756

If you've got any other ideas then go ahead and apply them, but I'm cool with merging this now if not.

**Comment by xayanide** [comment]
I see, another solution to that would be to track box ids independently.

Because it was relying solely on a sequential counter for box ID.

**Comment by NoelleTGS** [comment]
Yeah I was struggling to find a way to identify boxes that was both completely unique and wouldn't change upon every edit.

**Comment by xayanide** [comment]
Pushed a fix for it.
Please lmk if you've found another issue.
You may test it with this sample BBCode:
```
[box=ExampleA]
This is the content of the box labeled "ExampleA."
[/box]
[box=ExampleA]
This is the content of the 2nd box labeled "ExampleA."
[/box]

[box=ExampleB]
This is the content of the box labeled "ExampleB."
[box=ExampleB]
This is the content of the 2nd box labeled "ExampleB." inside the box labeled "ExampleB."
[/box]
[/box]
[box=ExampleB]
This is the content of the 3rd box labeled "ExampleB." outside the box labeled "ExampleB.
[/box]
try inserting more boxes here...
```

**Review by NoelleTGS — APPROVED** [review]
Still doesn't seem to behave perfectly :(

https://github.com/user-attachments/assets/6cf2465a-de04-493f-bebd-90e2bf3ba63b

I'm gonna merge this regardless since it seems like a really fringe case and again, is leagues better than what I had before. Feel free to create a new PR if you get any other ideas, thanks for the contribution 😁

**Pull request merged**
